var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "    xxxxx         xxx    x              x                     xx x              ",
   "     xxx           x     x              x                      x x              ",
   "      x            x     x                                                      ",
   "                         x                                         o            ",
   "                         o                                                      ",
   "                                                                  xxx           ",
   "                                                   yy            xx!xx          ",
   "                                    o o      yy                  x!!!x        o ",
   "                                                          yy     xx!xx      xxxx",
   "                            yy                                    xxx      x    ",
   "                                   yyyyyy                                  xx   ",
   "xxx                                       o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                            o  x  ",
   "  x      o   xxxx          o            x     x                              x  ",
   "  x  @       x  x                      x       x                 xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxx     yyy     xxxxxx       xxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                    x             x                  x     x                    ",
   "                    x!!!!!!!!!!!!!x                  x!!!!!x                    ",
   "                    x!!!!!!!!!!!!!x                  x!!!!!x                    ",
   "                    xxxxxxxxxxxxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxx!xxxxxxxxxxxxxxxx",
   "                                               x!x            x!x               ",
   "                                               xvx            xvx               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                             o                                                  ",
   "                                                         o                      ",
   "xx                         yyyyy                                                ",
   "  x           o                               yyyyyyyyyy    xxx xxxxxxx         ",
   "   x                                                                  xx+     o ",
   "   x          yy                  yy                                    xxxxxxxx",
   "   x                                       yy                                   ",
   "   x                yyy                  yy  yy                                 ",
   "   x                                    y                                     o ",
   "   x  @ o                  yy          y       y      yyyyy                     ",
   "   xxxxxxxx    yyy               yyy               o              xxxxxxxxxxxxxx",
   "          xx                                      yy           xxx              ",
   "          xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx              ",
   "           xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx               ",
   "            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                ",
   "            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                ",
   "            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                "],
  ["             x!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxx!!!!!!!!!!!!!!xxxxxxxx",
   "             x!!x                                  x!x   x!!!!!!!!!!!!!x        ",
   "             x!!x                                  x!x   x!xx!!!!!!!!xx         ",
   "             x!!x                                  x!x   x!x x!!xxx!x           ",
   "             x!!x                                  x!x   x!x x!!x x!x           ",
   "             x!!x                                  x!x   x!x  x!x x!x           ",
   "             x!!x                                  x!x   x!x  x!x x!x           ",
   "             x!!x                                  x!x   x!x  x!x x!x           ",
   "             x!!x                                  x!x   xvx  x!x x!x           ",
   "             x!!x                                  x!x   x x  x!x xvx           ",
   "             x |x                                  x!x   x x  x!x               ",
   "             x  x                                  xvx        x!x               ",
   "xxxxxxxxxxxxxx  x                                             xvx               ",
   "                                                                                ",
   "                                                                                ",
   "              o                                                              o  ",
   "                                                       o                        ",
   "       @                         o                          o         o        ",
   "xxxxxxxxxxxxxx  xxxxx+                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "             x| x    xxx                   xxx                                  ",
   "             x!!x       xxx            +xxx                                     ",
   "             x!!x          xxxxx   xxxxx                                        ",
   "             x!!x              x!!!x                                            "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                    k         k   k   kk   k                     k    k         ",
   "                     k   k   k    k   k k  k                     k    k         ",
   "                      k k k k     k   k  k k                                    ",
   "                       k   k      k   k   kk                   k        k       ",
   "     @                                                          k      k        ",
   "                                                                 kkkkkk         ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
